build-LambdaPowerToolsPython:
	mkdir -p "$(ARTIFACTS_DIR)/python/domain_services"
	cp -r ./src/* "$(ARTIFACTS_DIR)/python/ccb_itproy_toolbox/"
	python -m pip install -r requirements.txt -t "$(ARTIFACTS_DIR)/python/"