version = 0.1
[default.deploy.parameters]
stack_name = "pragma-assessment-layer-domainServicesLambda"
resolve_s3 = true
s3_prefix = "pragma-assessment-layer-domainServicesLambda"
region = "us-east-1"
confirm_changeset = true
image_repositories = []
capabilities = "CAPABILITY_IAM"
disable_rollback = true
