AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  DomainServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DomainServicesLayer
      Description: Library of the domain - Domain Driven Design
      ContentUri: .
      CompatibleRuntimes:
        - python3.8
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      LicenseInfo: MIT
    Metadata:
      BuildMethod: makefile
