AWSTemplateFormatVersion: 2010-09-09
Description: >-
  seconds-assessment-api
Transform:
  - AWS::Serverless-2016-10-31


Resources:
  assessmentApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: API dev of the assessment of Pragma - Second assessment
      StageName: dev
      OpenApiVersion: 3.0.3
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: "./api.yml"
      EndpointConfiguration:
        Type: REGIONAL
      # AccessLogSetting:
      #   DestinationArn: !GetAtt logGroupApi.Arn
      #   Format: $context.requestId
  # logGroupApi:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupClass: STANDARD
  #     LogGroupName: logGroupAssessmentApi
  #     RetentionInDays: 30
