AWSTemplateFormatVersion: 2010-09-09
Description: >-
  seconds-assessment-api
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  # Enable Logs
  Api:
    MethodSettings:
      - ResourcePath: "/*"
        HttpMethod: "*"
        DataTraceEnabled: True
        LoggingLevel: INFO
        MetricsEnabled: True
Resources:
  assessmentApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: API dev of the assessment of Pragma - Second assessment
      StageName: dev
      OpenApiVersion: 3.0.3
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: "./api.yml"
      EndpointConfiguration:
        Type: REGIONAL
      AccessLogSetting:
        DestinationArn: !GetAtt LogGroupAPI.Arn
        Format: $context.extendedRequestId $context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.requestId
  LogGroupAPI:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - "-"
        - - !Ref assessmentApi
          - access-logs
