version = 0.1
[default.deploy.parameters]
stack_name = "PRAGMA-ASSESSMENT-2024-1"
resolve_s3 = true
s3_prefix = "pragma-assessment-2024-1"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = [
    # API
    "StageNameEnvironment=dev",
]