AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  Roles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./infra/iam/template.yaml
  TablesDynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./infra/database/template.yaml
  # APIS
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./api/template.yaml
  GetBankServicesService:
    Type: AWS::CloudFormation::Stack
    DependsOn: Roles
    Properties:
      TemplateURL: ./handlers/apis/describe-services/template.yaml
  AutoRegisterClientService:
    Type: AWS::CloudFormation::Stack
    DependsOn: Roles
    Properties:
      TemplateURL: ./handlers/apis/register-client/template.yaml
  ModifyClientService:
    Type: AWS::CloudFormation::Stack
    DependsOn: Roles
    Properties:
      TemplateURL: ./handlers/apis/modify-client-by-comercial/template.yaml
  OrchestratorUsers:
    Type: AWS::CloudFormation::Stack
    DependsOn: Roles
    Properties:
      TemplateURL: ./handlers/integration-layer/orchestator/template.yaml
  MicroServiceClients:
    Type: AWS::CloudFormation::Stack
    DependsOn: Roles
    Properties:
      TemplateURL: ./handlers/services/clients-service/template.yaml
  MicroServiceProducts:
    Type: AWS::CloudFormation::Stack
    DependsOn: Roles
    Properties:
      TemplateURL: ./handlers/services/products-service/template.yaml