name: PipelineBuildSam
on: [push, pull_request]
jobs:
  make-build-and-deploy-in-aws:
    runs-on: ubuntu-latest
    steps:
      - name: First step - Make a checkout
        uses: actions/checkout@v4

      - name: Second step - Setup SAM environment
        uses: aws-actions/setup-sam@v2

      - name: Third step - Shows the SAM version
        run: sam --version

      - name: Fourth step - Change directory to 2024-1 and Build the template
        run: cd 2024-1/ && sam build --use-container

      - name: Fifth step - Shows everything is OK!
        run: echo "OK!"
