name: PipelineBuildAndDeploy
on: [push, pull_request]
jobs:
  make-build-and-deploy-in-aws-with-sam:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: First step - Make a checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Second step - Setup SAM environment
        uses: aws-actions/setup-sam@c6696d35f45207ec9622ec3235f1997c660e1ab2

      - name: Third step - Shows the SAM version
        run: sam --version

      - name: Fourth step - Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          REGION: us-east-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $REGION

      - name: Fifth step - Change directory to 2024-1 and Build the template
        run: |
          cd 2024-1/ 
          sam build --use-container 
          sam deploy

      - name: Sixth step - Shows everything is OK!
        run: echo "OK!"
  initialize-bd:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: make-build-and-deploy-in-aws-with-sam
    steps:
      - name: First step - Make a checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Second step - Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Third step - Execute script initializer of database
        run: |
          cd 2024-1/infra/database
          ./initialize_table.sh 

      - name: Sixth step - Shows everything is OK!
        run: echo "Database ready!"
